server:
  port: 8088
spring:
  application:
    name: gateway
  #以下路由规则表明,当访问http://localhost:8088/user/**会路由到http://localhost:8080/user/**
  cloud:
    gateway:
      #跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        #自定义的路由id,保持唯一
        - id: user-service
            #目标服务的地址
            uri: http://localhost:8080
            predicates:
              - Path=/login/**
            #请求前加/user
            filters:
              - PrefixPath=/user


