spring:
  datasource:
    name: shiro
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=GMT%2B8
    username: root
    password: issyu153
  application:
    name: provider
  cloud:
    nacos:
      server-addr: 101.37.20.199:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
